export interface pokemon{
    id:number,
    name:string,
    image:string
    height:number,
    weight:number,
    base_experience:number,
    stats:stats[],
    moves:string[],
    type:string[]
}

export interface pokelist{
    id:number,
    name:string,
   image:string
}

 interface stats{
    etiqueta:string,
    value:number
 }

 // Generated by https://quicktype.io

export interface FetchResponsePokemon {
    count:    number;
    next:     null;
    previous: null;
    results:  Result[];
}

export interface Result {
    name: string;
    url:  string;
}

// Generated by https://quicktype.io

export interface FetchAllTypes {
    count:    number;
    next:     null;
    previous: null;
    results:  Result[];
}

export interface Result {
    name: string;
    url:  string;
}

// Generated by https://quicktype.io

export interface TypeDetails {
    damage_relations:      DamageRelations;
    game_indices:          GameIndex[];
    generation:            Generation;
    id:                    number;
    move_damage_class:     Generation;
    moves:                 Generation[];
    name:                  string;
    names:                 Name[];
    past_damage_relations: any[];
    pokemon:               Pokemon[];
}

export interface DamageRelations {
    double_damage_from: Generation[];
    double_damage_to:   any[];
    half_damage_from:   any[];
    half_damage_to:     Generation[];
    no_damage_from:     Generation[];
    no_damage_to:       Generation[];
}

export interface Generation {
    name: string;
    url:  string;
}

export interface GameIndex {
    game_index: number;
    generation: Generation;
}

export interface Name {
    language: Generation;
    name:     string;
}

export interface Pokemon {
    pokemon: Generation;
    slot:    number;
}


// Generated by https://quicktype.io

export interface PokemonsPerType {
    name:     string;
    pokemons: PokemonElement[];
}

export interface PokemonElement {
    pokemon: PokemonPokemon;
    slot:    number;
}

export interface PokemonPokemon {
    name: string;
    url:  string;
}

// Generated by https://quicktype.io

export interface PokemonBasicInfo {
    id:    string;
    name:  string;
    image: string;
    type:  Type[];
}

export interface Type {
    name: string;
    slot: number;
}
